MyBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
    path('about/',views.about,name="about"),
    path('',views.homepage,name="home"),
    path('accounts/',include('accounts.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path,re_path
from . import views

app_name = 'accounts'

urlpatterns = [
     path('signup/',views.signup_view,name="signup"),
     path('login/',views.login_view,name = "login"),
     path('logout/',views.logout_view,name = "logout")

]

articles/urls.py
from django.urls import path,re_path
from . import views

app_name = 'articles'

urlpatterns = [

    path('',views.article_list,name="list"),
   path('create/',views.article_create, name="create"),
    re_path(r'^(?P<slug>[\w-]+)/$',views.article_detail,name="details"),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,default = None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','thumb']

MyBlog/views.py
from django.http import HttpResponse
from django.shortcuts import render
def about(request):
    return render(request,'about.html')
    #return HttpResponse('you will make it bhagyashree')

def homepage(request):
    return render(request,'homepage.html')
    #return HttpResponse('hi bhagyashree!! XOXO')

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            #login the User
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method =='POST':
        logout(request)
        return redirect('home')

articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles':articles})

def article_detail(request,slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form =forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="home"><h3>Login</h3></div>
<form class ="site-form" action = "{% url 'accounts:login' %}" method = "post">{% csrf_token %}
  {{form}}
  {% if request.GET.next %}
       <input type = "hidden" name ="next" value = "{{request.GET.next}}">
  {% endif %}
  <input type = "submit" value = "login">
  </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="home1"><h4>Signup</h4></div>
<form class ="site-form" action = "/accounts/signup/" method = "post">{% csrf_token %}
  {{form}}
  <input type = "submit" value = "signup">
  </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class = "create-article">
  <div class="home1"> create a new article </div>
  <form class="site-form" action = "{% url 'articles:create' %}" method = "post" enctype = "multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type = "submit" value = "create" >
    </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <h2>{{ article.title }}</h2>
        <img src = "{{ article.thumb.url}}">
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<div class ="home1"><h5>Articles</h5></div>
<div class = "articles">
  {% for article in articles %}
  <div class = "article">
    <h2><a href ="{% url 'articles:details' slug=article.slug %}">{{article.title}}</a></h2>
    <p>{{article.snippet}}</p>
    <p>{{article.date}}</p>
    <p class="author">added by {{ article.author.username }}</p>
  </div>
    {% endfor %}
</div>
{% endblock %}

templates/about.html
{% extends 'base_layout.html' %}
{% block content %}

<div class="home"><h3>About</h3></div>



{% endblock %}

templates/base_layout.html
{% load static  %}
<!DOCTYPE html>
<html>
    <head>

        <meta name="viewport" content="width=device-width, initial-scale=1.0" charset="utf-8">
        <title>BlogForFun</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <header class="wrapper">

          <div class = "logo"> <a href="{% url 'home' %}"><img src ="{% static 'logo.png' %}" alt="BlogForFun"></a></div>
             <nav>
                <ul>
                    {% if user.is_authenticated %}
                      <li><a href="{% url 'about' %}">ABOUT<br>US</a></li>
                    <li>

                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">LOGOUT</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">NEW ARTICLE</a></li>
                    <li><a href="{% url 'articles:list' %}" class="highlight"> ARTICLES</a></li>
                    {% else %}
                    <li><a href="{% url 'about' %}" class="highlight">ABOUT</a></li>
                    <li><a href="{% url 'accounts:login' %}">LOGIN</a></li>
                    <li><a href="{% url 'accounts:signup' %}">SIGNUP</a></li>
                    {% endif %}
                </ul>
          </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
        <div class="footer">
          contact us:98278*****
        </div>
    </body>
</html>

templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="home"><h2> READ, WRITE AND GROW WITH US!!!!<br><a href="{% url 'accounts:signup' %}"><button><h4>JOIN NOW</h4></button></a>
</div>

{% endblock %}